name: Serv00/CT8 Login Tasks

on:
  workflow_dispatch:
  schedule:
    # 每月 7,17,27 号运行一次, 运行时间为 13:14
    - cron: "14 13 7,17,27 * *"
  # push:
  #   paths-ignore:
  #     - "LICENSE"
  #     - "README.md"
  #     - "README_**"
  #     - "README-**"
  #   branches:
  #     - main

env:
  ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

jobs:  
  login:  
    runs-on: ubuntu-latest  
  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v4

      - name: Create accounts.json
        run: echo "$ACCOUNTS_JSON" > accounts.json
  
      - name: Set up Node.js  
        uses: actions/setup-node@v4  
        with:  
          node-version: '20.x'  
  
      - name: Install dependencies  
        run: npm install puppeteer axios
  
      - name: Login into Serv00/CT8
        run: |  
          set -e  
          xvfb-run --server-args="-screen 0 1280x1024x24" node src/main.js

      - name: Init git environment
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "hxulin"
          git config --global user.email "1455936807@qq.com"

      - name: Update modified time
        run: |
          echo `date "+%Y-%m-%d %H:%M:%S"` > last-modified.txt
          git add -A
          git commit -m '更新构建时间'
          git push git@github.com:hxulin/serv00-auto-scripts.git main